GetYahooSymbols=function(){
  Symbols=c("1COV.DE", "A1OS.DE", "A4Y.DE", "AAD.DE", "AAG.DE", "AAH.F", 
"AAH3.DE", "AAQ.DE", "ACWN.DE", "ACX.DE", "ADD.DE", "ADJ.DE", 
"ADL.DE", "ADS.DE", "ADV.DE", "AFX.DE", "AIR.DE", "AIXA.DE", 
"ALV.DE", "AM3D.DE", "AOF.DE", "AOX.DE", "APM.DE", "ARL.DE", 
"ART.DE", "ASL.DE", "AT1.DE", "AVES.DE", "B4B.DE", "B4B3.DE", 
"B5A.DE", "B8F.DE", "BAS.DE", "BAYN.DE", "BBZA.DE", "BC8.DE", 
"BDT.DE", "BEI.DE", "BFSA.DE", "BIO.DE", "BIO3.DE", "BMW.DE", 
"BMW3.DE", "BNN.DE", "BNR.DE", "BOSS.DE", "BSL.DE", "BST.DE", 
"BTBB.F", "BVB.DE", "BYW.DE", "BYW6.DE", "CAP.DE", "CBK.DE", 
"CCAP.DE", "CE2.DE", "CEC.DE", "CEV.DE", "COK.DE", "COM.DE", 
"CON.DE", "COP.DE", "CPX.DE", "CSH.DE", "CSQ.DE", "CWC.DE", "DAI.DE", 
"DAM.DE", "DB1.DE", "DBAN.DE", "DBD.DE", "DBK.DE", "DEQ.DE", 
"DEX.DE", "DEZ.DE", "DHER.DE", "DIC.F", "DKG.DE", "DLG.DE", "DMP.DE", 
"DMRE.DE", "DPW.DE", "DRI.DE", "DRW3.DE", "DRW8.DE", "DTE.DE", 
"DUE.DE", "DWNI.DE", "DWS.DE", "E4C.DE", "ECK.DE", "ECX.DE", 
"ED4.DE", "EIN3.DE", "ELB.DE", "ELG.DE", "EOAN.DE", "ERMK.DE", 
"EUCA.DE", "EUZ.DE", "EV4.DE", "EVD.DE", "EVK.DE", "EVT.DE", 
"EXC.DE", "EXN.DE", "F3C.DE", "FAA.DE", "FBEN.DE", "FEV.DE", 
"FIE.DE", "FME.DE", "FNTN.DE", "FPE.DE", "FPE3.DE", "FPH.DE", 
"FRA.DE", "FRE.DE", "FRU.DE", "G1A.DE", "G24.DE", "GBF.DE", "GFT.DE", 
"GGS.DE", "GIL.DE", "GKS.DE", "GLJ.DE", "GME.DE", "GMM.DE", "GSC1.DE", 
"GWD.DE", "GWI1.DE", "GXI.DE", "GYC.DE", "H24.DE", "HAB.SG", 
"HAW.DE", "HBH.DE", "HBM.DE", "HDD.DE", "HEI.DE", "HEN.DE", "HEN3.DE", 
"HFG.DE", "HHFA.DE", "HLAG.DE", "HLE.DE", "HLG.DE", "HNL.DE", 
"HNR1.DE", "HOC.DE", "HOT.DE", "HYQ.DE", "IFX.DE", "IGY.DE", 
"INH.DE", "INS.DE", "IS7.DE", "ISH2.DE", "ISR.DE", "IVU.DE", 
"IVX.DE", "IXX.DE", "JEN.DE", "JST.DE", "JUN3.DE", "K1R.DE", 
"KCO.DE", "KGX.DE", "KRN.DE", "KSC.DE", "KU2.DE", "KWS.DE", "LEG.DE", 
"LEI.DE", "LEO.DE", "LHA.DE", "LIN.DE", "LNSX.DE", "LO24.DE", 
"LPK.DE", "LXS.DE", "M3V.DE", "M5Z.DE", "MBB.DE", "MDG1.DE", 
"MED.DE", "MGNK.DE", "MLP.DE", "MOR.DE", "MRK.DE", "MTX.DE", 
"MUV2.DE", "MVV1.DE", "MXHN.F", "MZX.DE", "NaN", "NaN", "NaN", 
"NaN", "NaN", "NAN", "NDA.DE", "NDX1.DE", "NEM.DE", "NFN.DE", 
"NOEJ.DE", "NXU.DE", "O1BC.DE", "O2C.DE", "O2D.DE", "O4B.DE", 
"OHB.DE", "OSP2.DE", "OSR.DE", "PA8.DE", "PBB.DE", "PCZ.DE", 
"PFV.DE", "PGN.DE", "PNE3.DE", "PS4.F", "PSAN.DE", "PSM.DE", 
"PTZIF", "PUM.DE", "PWO.DE", "QIA.DE", "QSC.DE", "RAA.DE", "RHK.DE", 
"RHM.DE", "RIB.DE", "RKET.DE", "RRTL.DE", "RSL2.DE", "RWE.DE", 
"RWE3.DE", "RY8.DE", "S4A.DE", "S92.DE", "SAE.DE", "SANT.DE", 
"SAP.DE", "SAX.DE", "SBS.DE", "SDF.DE", "SEN.DE", "SF3.DE", "SFP1.DE", 
"SFQ.DE", "SGL.DE", "SHA.DE", "SHF.DE", "SHL.DE", "SIE.DE", "SIS.DE", 
"SIX2.DE", "SIX3.DE", "SJJ.DE", "SKB.DE", "SLT.DE", "SMHN.DE", 
"SNG.DE", "SNH.DE", "SOW.DE", "SPR.DE", "SRT.DE", "SRT3.DE", 
"STM.DE", "SUR.DE", "SY1.DE", "SYT.DE", "SYZ.DE", "SZG.F", "SZU.DE", 
"TC1.DE", "TEG.DE", "TGHN.DE", "TGT.DE", "TIM.DE", "TKA.DE", 
"TLG.DE", "TLI.DE", "TLX.DE", "TPE.DE", "TTI.DE", "TTK.DE", "TTR1.DE", 
"ULC.DE", "UN01.DE", "UTDI.DE", "UUU.DE", "V3V.DE", "V6C.DE", 
"VAO.DE", "VAR1.DE", "VBK.DE", "VBX.DE", "VIB3.DE", "VNA.DE", 
"VOS.DE", "VOW.DE", "VOW3.DE", "VQT.DE", "VSC.DE", "VT9.DE", 
"WAC.DE", "WAF.DE", "WCH.DE", "WDI.DE", "WDLK.DE", "WIN.DE", 
"WL6.DE", "WSU.DE", "WUG.DE", "WUG3.DE", "WUW.DE", "XMY.F", "YOC.DE", 
"YSN.DE", "ZAL.DE", "ZIL2.DE", "ZO1.DE")
  return(Symbols)
}